### ISSUE TITLE
Item enchant level is wrong

### ISSUE THREAD

**Issue by sh1ny** [albion-packet-hooking/AlbionPacketHandler#13]
Hey,
The logged item enchant level is +1 of what it is actually.
Here's an example:

https://i.imgur.com/vteifsZ.png

Also realmbreaker is not properly parsed ( being 4.3 and not t5 ).

**Comment by albion-packet-hooking** [comment]
Sounds like the items.bin is incorrect, probably localization too.

The resources folder will contain a list of encrypted bin files. If a new release occurs you will need to drop the files from the game folder and the program will automate decrypting them on the next load up.

Files are found at:
[Game Installation Dir]/game/Albion-Online_Data/StreamingAssets/GameData

**Comment by sh1ny** [comment]
That did the trick, ty !

https://i.imgur.com/WfgRUmv.png
